### ISSUE TITLE
Vertices not removed from "vertices" index

### ISSUE THREAD

**Issue by alexblanquart** [Riduidel/gaedo#57] opened 2013-04-30 07:57 UTC
The delete of vertex seems to pass through the GraphUtils#removeSafely, which does not remove the vertex from "vertices" index. Then, the transaction could be in an unsafely mode when trying to use this vertex, which should not be accessible anymore.

Indeed, Gaedo must handle all CRUD operations on "vertices" and "edges'" indices, that Blueprints new version does not handle anymore.

**Comment by Riduidel** [comment] 2013-04-30 09:09
Duplicate of #56

**Closed as completed by Riduidel** 2013-04-30 09:09 UTC
